# Form implementation generated from reading ui file 'models_tool/modelssettings.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_modelsOptionsDialog(object):
    def setupUi(self, modelsOptionsDialog):
        modelsOptionsDialog.setObjectName("modelsOptionsDialog")
        modelsOptionsDialog.resize(506, 250)
        modelsOptionsDialog.setMinimumSize(QtCore.QSize(5, 0))
        self.gridLayout_2 = QtWidgets.QGridLayout(modelsOptionsDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.confimModelOptionsButton = QtWidgets.QPushButton(parent=modelsOptionsDialog)
        self.confimModelOptionsButton.setObjectName("confimModelOptionsButton")
        self.gridLayout.addWidget(self.confimModelOptionsButton, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=modelsOptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nn_option_checkbox = QtWidgets.QCheckBox(parent=modelsOptionsDialog)
        self.nn_option_checkbox.setChecked(True)
        self.nn_option_checkbox.setObjectName("nn_option_checkbox")
        self.gridLayout.addWidget(self.nn_option_checkbox, 2, 1, 1, 1)
        self.gp_option_checkbox = QtWidgets.QCheckBox(parent=modelsOptionsDialog)
        self.gp_option_checkbox.setChecked(True)
        self.gp_option_checkbox.setObjectName("gp_option_checkbox")
        self.gridLayout.addWidget(self.gp_option_checkbox, 3, 1, 1, 1)
        self.svr_option_checkbox = QtWidgets.QCheckBox(parent=modelsOptionsDialog)
        self.svr_option_checkbox.setChecked(True)
        self.svr_option_checkbox.setObjectName("svr_option_checkbox")
        self.gridLayout.addWidget(self.svr_option_checkbox, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(modelsOptionsDialog)
        QtCore.QMetaObject.connectSlotsByName(modelsOptionsDialog)

    def retranslateUi(self, modelsOptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        modelsOptionsDialog.setWindowTitle(_translate("modelsOptionsDialog", "Dialog"))
        self.confimModelOptionsButton.setText(_translate("modelsOptionsDialog", "Confrim"))
        self.label.setText(_translate("modelsOptionsDialog", "Choose models to show:"))
        self.nn_option_checkbox.setText(_translate("modelsOptionsDialog", "Neural Network"))
        self.gp_option_checkbox.setText(_translate("modelsOptionsDialog", "GP"))
        self.svr_option_checkbox.setText(_translate("modelsOptionsDialog", "SVR"))
